Update demoaction.yaml

diff --git a/.github/workflows/demoaction.yaml b/.github/workflows/demoaction.yaml
--- a/.github/workflows/demoaction.yaml
+++ b/.github/workflows/demoaction.yaml
@@ -7,9 +7,27 @@ jobs:
   backwards-compatibility:
     runs-on: ${{ matrix.os }}
     strategy:
+      fail-fast: false
       matrix:
-        os: [ubuntu-latest, windows-latest]
-        node: [18.x, 20.x, 21.x]
+        include:
+          - os: ubuntu-latest
+            node: 16.x
+
+          - os: ubuntu-latest
+            node: 18.x
+          - os: ubuntu-latest
+            node: 20.x
+          - os: ubuntu-latest
+            node: 21.x
+            tag: experimental
+
+          - os: windows-latest
+            node: 18.x
+          - os: windows-latest
+            node: 20.x
+          - os: windows-latest
+            node: 21.x
+
     name: ${{ matrix.os }}-${{ matrix.node }}
 
     steps:
@@ -18,5 +36,16 @@ jobs:
         with:
           node-version: ${{ matrix.node }}
 
+      - name: Fail if experimental
+        if: ${{ matrix.tag == 'experimental' }}
+        run: |
+          echo "This is an experimental configuration. Failing intentionally."
+          exit 1
+
       - name: Perform some tests
-        run: echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"
+        run: |
+          echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"
+          sleep 10
+
+      - name: Upload test results
+        run: echo "Uploading test results"
